// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7AYFqdgQ1q2DE4NQkSf4H4HL7ab4ZhIA',
    appId: '1:358935174408:web:1e31e056326af2a2f2a0bd',
    messagingSenderId: '358935174408',
    projectId: 'sagada-tour-planner-and-map',
    authDomain: 'sagada-tour-planner-and-map.firebaseapp.com',
    storageBucket: 'sagada-tour-planner-and-map.firebasestorage.app',
    measurementId: 'G-K6JT77DM41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp73OfWNg7pGMFCe6QVdSCkyPBhwof9dI',
    appId: '1:358935174408:android:2534ecf965e7be2ef2a0bd',
    messagingSenderId: '358935174408',
    projectId: 'sagada-tour-planner-and-map',
    storageBucket: 'sagada-tour-planner-and-map.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4R_gnFU0PWBZU73nCkf_oRXe1bCIVn2k',
    appId: '1:358935174408:ios:952f18028f222aedf2a0bd',
    messagingSenderId: '358935174408',
    projectId: 'sagada-tour-planner-and-map',
    storageBucket: 'sagada-tour-planner-and-map.firebasestorage.app',
    androidClientId: '358935174408-dfsvtvl57ijopenc5vuoun4j2g4bomt2.apps.googleusercontent.com',
    iosClientId: '358935174408-morc6me6u4t2qti12uo532n9e6mu9t45.apps.googleusercontent.com',
    iosBundleId: 'com.example.sagadatourplannerandmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4R_gnFU0PWBZU73nCkf_oRXe1bCIVn2k',
    appId: '1:358935174408:ios:952f18028f222aedf2a0bd',
    messagingSenderId: '358935174408',
    projectId: 'sagada-tour-planner-and-map',
    storageBucket: 'sagada-tour-planner-and-map.firebasestorage.app',
    androidClientId: '358935174408-dfsvtvl57ijopenc5vuoun4j2g4bomt2.apps.googleusercontent.com',
    iosClientId: '358935174408-morc6me6u4t2qti12uo532n9e6mu9t45.apps.googleusercontent.com',
    iosBundleId: 'com.example.sagadatourplannerandmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7AYFqdgQ1q2DE4NQkSf4H4HL7ab4ZhIA',
    appId: '1:358935174408:web:b8adccd1a18f8bdaf2a0bd',
    messagingSenderId: '358935174408',
    projectId: 'sagada-tour-planner-and-map',
    authDomain: 'sagada-tour-planner-and-map.firebaseapp.com',
    storageBucket: 'sagada-tour-planner-and-map.firebasestorage.app',
    measurementId: 'G-ZT80RVMQ01',
  );

}