import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

// --- 1. ADD THE APP CHECK IMPORT ---
import 'package:firebase_app_check/firebase_app_check.dart'; // <-- ADD THIS

import 'screens/login_screen.dart';
import 'screens/terms_screen.dart';
import 'screens/register_screen.dart';
import 'screens/splash_screen.dart';

// Helper function to create a MaterialColor from a single Color.
MaterialColor createMaterialColor(Color color) {
  List strengths = <double>[.05];
  final swatch = <int, Color>{};
  final int r = color.red, g = color.green, b = color.blue;

  for (int i = 1; i < 10; i++) {
    strengths.add(0.1 * i);
  }
  for (var strength in strengths) {
    final double ds = 0.5 - strength;
    swatch[(strength * 1000).round()] = Color.fromRGBO(
      r + ((ds < 0 ? r : (255 - r)) * ds).round(),
      g + ((ds < 0 ? g : (255 - g)) * ds).round(),
      b + ((ds < 0 ? b : (255 - b)) * ds).round(),
      1,
    );
  }
  return MaterialColor(color.value, swatch);
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  /*await FirebaseAppCheck.instance.activate(
    webProvider: ReCaptchaV3Provider(
      '6Ldm6forAAAAAPCutYaWnsQI8x5KM2ZGUCOfB39J',
    ),
    androidProvider: AndroidProvider.debug,
    appleProvider: AppleProvider.appAttest,
  );

  print('Firebase App Check activated successfully.'); // Add this line*/
  runApp(const SagadaTourPlannerApp());
}

class SagadaTourPlannerApp extends StatelessWidget {
  const SagadaTourPlannerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sagada Tour Planner',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        fontFamily: 'Roboto',
        primarySwatch: createMaterialColor(const Color(0xFF3A6A55)),

        // (Optional) You can also set the primary color directly for consistency
        primaryColor: const Color(0xFF3A6A55),
        useMaterial3: true,
      ),
      home: const SplashScreen(),
      routes: {
        '/terms': (context) => const TermsAgreementScreen(),
        '/home': (context) => const Placeholder(),
        '/login': (context) => const LoginScreen(),
        '/register': (context) => const RegisterScreen(),
      },
    );
  }
}
