import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

// ⭐️ --- ADD THESE IMPORTS --- ⭐️
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'providers/theme_provider.dart';
// ⭐️ --- END OF IMPORTS --- ⭐️

import 'screens/login_screen.dart';
import 'screens/terms_screen.dart';
import 'screens/register_screen.dart';
import 'screens/splash_screen.dart';
import 'auth_wrapper.dart';
import 'screens/map_homescreen.dart';
import 'package:flutter_facebook_auth/flutter_facebook_auth.dart';
import 'package:flutter/services.dart';

// Your existing createMaterialColor function...
MaterialColor createMaterialColor(Color color) {
  List strengths = <double>[.05];
  final swatch = <int, Color>{};
  final int r = color.red, g = color.green, b = color.blue;

  for (int i = 1; i < 10; i++) {
    strengths.add(0.1 * i);
  }
  for (var strength in strengths) {
    final double ds = 0.5 - strength;
    swatch[(strength * 1000).round()] = Color.fromRGBO(
      r + ((ds < 0 ? r : (255 - r)) * ds).round(),
      g + ((ds < 0 ? g : (255 - g)) * ds).round(),
      b + ((ds < 0 ? b : (255 - b)) * ds).round(),
      1,
    );
  }
  return MaterialColor(color.value, swatch);
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // ⭐️ --- ADD THIS --- ⭐️
  // Load preferences *before* the app runs
  final prefs = await SharedPreferences.getInstance();
  // ⭐️ --- END OF ADDITION --- ⭐️

  FirebaseFirestore.instance.settings = const Settings(
    persistenceEnabled: true,
    cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
  );

  // ... (your existing debug block) ...

  // ⭐️ --- MODIFIED THIS --- ⭐️
  // Wrap your app in the provider
  runApp(
    ChangeNotifierProvider(
      create: (context) => ThemeProvider(prefs), // Pass in the prefs
      child: const SagadaTourPlannerApp(),
    ),
  );
  // ⭐️ --- END OF MODIFICATION --- ⭐️
}

class SagadaTourPlannerApp extends StatelessWidget {
  const SagadaTourPlannerApp({super.key});

  @override
  Widget build(BuildContext context) {
    // ⭐️ --- ADD THIS --- ⭐️
    // Consume the provider to get the current theme
    final themeProvider = context.watch<ThemeProvider>();
    final Color primaryColor = const Color(0xFF3A6A55);
    // ⭐️ --- END OF ADDITION --- ⭐️

    return MaterialApp(
      title: 'Sagada Tour Planner',
      debugShowCheckedModeBanner: false,

      // --- START OF THEME MODIFICATION ---
      // 1. Set the ThemeMode from the provider
      themeMode: themeProvider.themeMode,

      // 2. Define your light theme
      theme: ThemeData(
        fontFamily: 'Roboto',
        primarySwatch: createMaterialColor(primaryColor),
        primaryColor: primaryColor,
        brightness: Brightness.light, // Explicitly set brightness
        useMaterial3: true,
        // (You can add more light-specific colors here)
      ),

      // 3. Define your dark theme
      darkTheme: ThemeData(
        fontFamily: 'Roboto',
        primarySwatch: createMaterialColor(primaryColor),
        primaryColor: primaryColor,
        brightness: Brightness.dark, // Explicitly set brightness
        useMaterial3: true,
        // (You can add more dark-specific colors here)
      ),
      // --- END OF THEME MODIFICATION ---

      home: const SplashScreen(),
      routes: {
        '/terms': (context) => const TermsAgreementScreen(),
        '/home': (context) => const AuthWrapper(),
        '/map_home': (context) => const MapScreen(),
        '/login': (context) => const LoginScreen(),
        '/register': (context) => const RegisterScreen(),
      },
    );
  }
}
